services:
  gateway:
    image: kobogg/gateway:latest
    restart: unless-stopped
    build:
      context: gateway
      dockerfile: app/Dockerfile
    depends_on:
      - backend
      - frontend
    expose:
      - 80
    networks:
      - vps-traefik
      - default
    labels:
      - "traefik.docker.network=vps-traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.kobogg.rule=Host(`kobo.gg`, `www.kobo.gg`)"
      - "traefik.http.routers.kobogg.entrypoints=websecure"
      - "traefik.http.routers.kobogg.tls.certresolver=myresolver"
  backend:
    image: kobogg/backend:latest
    restart: unless-stopped
    build:
      context: ./backend/api
      dockerfile: ../Dockerfile
    env_file:
      - ./backend/.env.prod
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Migrations service that runs once during deployment
  migrations:
    image: kobogg/backend:latest
    env_file:
      - ./backend/.env.prod
    command: ./apply-migrations.sh
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  frontend:
    image: kobogg/frontend:latest
    restart: unless-stopped
    env_file:
      - ./frontend/.env.prod.local
    build:
      context: ./frontend
      dockerfile: docker/prod/Dockerfile
    networks:
      - default
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - ./.env.local
    volumes:
      - kobogg_db_volume:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  default:
  vps-traefik:
    external: true
    
volumes:
  kobogg_db_volume:
