/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type ApiTokenResponse = {
  token: string;
  user: UserDto;
};

export type BookDto = {
  /**
   * @format uuid
   */
  id: string;
  fileName: string;
  originalFileName: string;
  /**
   * @format int64
   */
  fileSize: number;
  downloadUrl: string;
  /**
   * @default null
   */
  kepubDownloadUrl?: string | null;
};

export type BundleBooksResponse = {
  books: BookDto[];
  /**
   * @format date-time
   */
  expiresAt: string;
};

export type EpubUploadUrlRequestDto = {
  /**
   * @format uuid
   */
  tmpBookBundleId: string;
  /**
   * @maxLength 255
   * @minLength 0
   */
  fileName: string;
  /**
   * @maxLength 255
   * @minLength 0
   */
  contentType: string;
};

export type EpubUploadUrlResponseDto = {
  url: string;
  key: string;
  /**
   * @format uuid
   */
  pendingBookId: string;
};

export type ErrorResponse = {
  code: string;
};

export type FinalizeBooksRequestDto = {
  /**
   * @format uuid
   */
  tmpBookBundleId: string;
};

export type FinalizeBooksResponseDto = {
  /**
   * @format int32
   */
  convertedCount: number;
  /**
   * @format uuid
   */
  tmpBookBundleId: string;
};

export type GuidResponse = {
  /**
   * @format uuid
   */
  id: string;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type TmpBookBundleDto = {
  /**
   * @format uuid
   */
  id: string;
  shortUrlCode: string;
  /**
   * @format date-time
   */
  expiresAt: string;
};

export type UserDto = {
  /**
   * @format uuid
   */
  id: string;
  email: string;
};

export type UserInfoResponse = {
  user: UserDto;
};

export type UserLoginDto = {
  email: string;
  /**
   * @maxLength 6
   * @minLength 6
   */
  code: string;
};

export type UserRegistrationDto = {
  email: string;
};
