/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type StaticContentResponse = {
  terms: string;
  privacy: string;
};

export type ChangeEmailRequest = {
  newEmail: string;
};

export type ValidationErrorResponseRef = {
  /**
   * @example validation_error
   */
  code: string;
  errors: ValidationErrorItem[];
};

export type GenericErrorResponseRef = {
  /**
   * @example not_found
   */
  code: 'already_exists' | 'not_found';
};

export type ServerErrorRef = {
  /**
   * @example https://tools.ietf.org/html/rfc2616#section-10
   */
  type: string;
  /**
   * @example An error occurred
   */
  title: string;
  /**
   * @example 500
   */
  status: number;
  /**
   * @example Internal Server Error
   */
  detail: string;
};

export type ChangeEmailConfirmationRequest = {
  token: string;
};

export type NotFoundErrorRef = {
  /**
   * @example not_found
   */
  code: string;
};

export type UserInfoResponse = {
  user: UserDto;
};

export type AuthRequiredErrorResponse = {
  /**
   * @default https://tools.ietf.org/html/rfc2616#section-10
   * @example https://tools.ietf.org/html/rfc2616#section-10
   */
  type: string;
  /**
   * @default An error occurred
   * @example An error occurred
   */
  title: string;
  /**
   * @default 401
   * @example 401
   */
  status: number;
  /**
   * @default Unauthorized
   * @example Unauthorized
   */
  detail: string;
};

export type EmailPrefsResponse = {
  /**
   * @default true
   */
  enableMarketingEmails: boolean;
  /**
   * @default true
   */
  enableNotifications: boolean;
};

export type SetEmailPrefsRequest = {
  /**
   * @default true
   */
  enableMarketingEmails: boolean;
  /**
   * @default true
   */
  enableNotifications: boolean;
};

export type UnsubscribeFromMarketingEmailsRequest = {
  unsubscribeToken: string;
};

export type LoginRequest = {
  email: string;
  otp: string;
};

export type LoginSuccessResponse = {
  user: UserDto;
  apiToken: string;
};

export type OtpRequest = {
  email: string;
};

export type OtpSuccessResponse = {
  /**
   * @format date-time
   */
  otpExpiresAt: string;
};

export type OtpErrorResponseRef = {
  code: 'user_not_found' | 'valid_otp_already_exists';
};

export type VerifyEmailRequest = {
  token: string;
};

export type DealOwnerRegistrationRequest = {
  email: string;
  name: string;
};

export type DealOwnerRegistrationSuccessResponse = {
  /**
   * @format uuid
   */
  userId: string;
  apiToken: string;
  user: UserDto;
};

export type RegistrationErrorResponseRef = {
  code: 'already_exists' | 'city_not_found';
};

export type GetDealByIdResponse = {
  deal: DealDto;
  mandate: PublicMandateDto;
};

export type GetUserDealsResponse = {
  deals: UserDealDto[];
};

export type SaveDealRequest = {
  mandateId: string;
  deal: DealDto;
  dealOwner: DealOwnerDto;
  attachments: string[];
};

export type SaveDealSuccessResponse = {
  /**
   * @format uuid
   */
  id: string;
  user: UserDto | null;
  apiToken: string | null;
};

export type InvestorRegistrationRequest = {
  email: string;
  basicInfo: InvestorBasicInfoDto;
};

export type InvestorRegistrationSuccessResponse = {
  /**
   * @format uuid
   */
  userId: string;
  apiToken: string;
  user: UserDto;
};

export type SaveInvestorProfileDraftRequest = {
  step: number | null;
  draft: InvestorProfileDraftDto;
};

export type SaveInvestorProfileDraftSuccessResponse = {
  profileDraft: InvestorProfileDraftDto;
  lastCompletedStep: number | null;
};

export type SaveInvestorVerificationDataSuccessResponse = {
  /**
   * @format uuid
   */
  profileId: string;
  status: InvestorProfileStatusEnum;
  profile: InvestorProfileDto;
};

export type GetMandatesResponse = {
  mandates: MandateDto[];
};

export type GetMandateByIdResponse = {
  mandate: MandateDto;
};

export type GetPublicMandatesResponse = {
  mandates: PublicMandateDto[];
};

export type GetPublicMandateByIdResponse = {
  mandate: PublicMandateDto;
};

export type SaveMandateDraftRequest = {
  step: number | null;
  draft: MandateDraftDto;
};

export type SaveMandateSuccessResponse = {
  /**
   * @format uuid
   */
  mandateId: string;
};

export type SaveMandateDraftSuccessResponse = {
  mandateDraft: MandateDraftDto;
  lastCompletedStep: number | null;
};

export type CountriesResponse = {
  countries: CountryDto[];
};

export type AdminGetAllDealsResponse = {
  deals: AdminDealDto[];
};

export type AdminGetDealByIdResponse = {
  deal: AdminDealDto;
};

export type AdminGetInvestorByIdResponse = {
  investor: InvestorFullProfileDto;
};

export type AdminGetInvestorsResponse = {
  investors: InvestorFullProfileDto[];
};

export type AdminGetAllMandatesResponse = {
  mandates: MandateDto[];
};

export type UploadAttachmentRequest = {
  filename: string;
};

export type SignedUploadUrl = {
  uploadUrl: string;
  /**
   * @format uuid
   */
  attachmentId: string;
  /**
   * @format date-time
   */
  expiresAt: string;
};

export type GetInitResponse = {
  /**
   * @default null
   */
  user: UserDto | null;
  txt: {
    [key: string]: string;
  };
};

export type TxtRequest = {
  key: string;
  value: string;
};

export type ValidationErrorItem = {
  /**
   * @example This value is not a valid email address.
   */
  message: string;
  /**
   * @example [email]
   */
  path: string;
  /**
   * @example email
   */
  label: string;
};

export type UserDto = {
  /**
   * @format uuid
   */
  id: string;
  email: string;
  roles: string[];
  /**
   * @default null
   */
  investorProfile: InvestorProfileDto | null;
};

export type DealDto = {
  /**
   * @default false
   */
  dealSources: boolean;
  /**
   * @default false
   */
  investmentStrategy: boolean;
  /**
   * @default null
   */
  realEstate: DealRealEstateDto | null;
  /**
   * @default null
   */
  privateEquity: DealPrivateEquityDto | null;
  /**
   * @default null
   */
  trophyAssets: DealTrophyAssetsDto | null;
  /**
   * @default null
   */
  funds: DealFundsDto | null;
  /**
   * @default null
   */
  taxAdvantaged: DealTaxAdvantagedDto | null;
  /**
   * @default false
   */
  instrumentType: boolean;
  /**
   * @default false
   */
  syndicationPreference: boolean;
  /**
   * @default false
   */
  dealBreakers: boolean;
  /**
   * @default false
   */
  minimumReturnTarget: boolean;
  /**
   * @default false
   */
  sponsorTrackRecord: boolean;
  /**
   * @default false
   */
  geographicalRestrictions: boolean;
  notes: {
    [key: string]: string;
  };
  /**
   * @default null
   */
  description: string | null;
  /**
   * @default null
   */
  status: DealStatusEnum | null;
};

export type PublicMandateDto = {
  /**
   * @format uuid
   */
  id: string;
  dealSources: any[];
  investmentStrategy: string | null;
  otherStrategy: string | null;
  realEstate: MandateRealEstateDto | null;
  privateEquity: MandatePrivateEquityDto | null;
  trophyAssets: MandateTrophyAssetsDto | null;
  funds: MandateFundsDto | null;
  taxAdvantaged: MandateTaxAdvantagedDto | null;
  instrumentType: string | null;
  otherInstrumentType: string | null;
  syndicationPreference: string | null;
  dealBreakers: string | null;
  minimumReturnTarget: string | null;
  minimumReturnTargetCustomValue: string | null;
  sponsorTrackRecord: string | null;
  geographicalRestrictions: string | null;
  additionalDetails: string | null;
};

export type UserDealDto = {
  /**
   * @format uuid
   */
  dealId: string;
  deal: DealDto;
  mandate: PublicMandateDto;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type DealOwnerDto = {
  name: string;
  email: string;
  phone: string | null;
  role: DealOwnerRoleEnum;
};

export type InvestorBasicInfoDto = {
  name: FullNameDto;
  countryId: number;
  stateOfResidence: string | null;
  referralSource: string;
};

export type InvestorProfileDraftDto = {
  /**
   * @default null
   */
  fullName: FullNameDto | null;
  /**
   * @default null
   */
  countryOfResidence: number | null;
  /**
   * @default null
   */
  stateOfResidence: string | null;
  /**
   * @default null
   */
  referralSource: string | null;
  /**
   * @default null
   */
  phoneNumber: string | null;
  /**
   * @default null
   */
  linkedinUrl: string | null;
  /**
   * @default null
   */
  investorType: string | null;
  /**
   * @default false
   */
  acceptedNoAlternativeUse: boolean;
  /**
   * @default false
   */
  acceptedRiskAcknowledgement: boolean;
  /**
   * @default false
   */
  acceptedLegalAcknowledgement: boolean;
  /**
   * @default false
   */
  acceptedAnonymousDistribution: boolean;
  /**
   * @default null
   */
  accreditedInvestorStatus: string | null;
  /**
   * @default false
   */
  accreditationConfirmation: boolean;
  /**
   * @default null
   */
  lpInvestingExperience: string | null;
  /**
   * @default null
   */
  deployedAmount: string | null;
  /**
   * @default null
   */
  expectedDeploymentAmount: string | null;
  /**
   * @default null
   */
  netWorth: string | null;
};

export type InvestorProfileStatusEnum =
  | 'INCOMPLETE'
  | 'PENDING_VERIFICATION'
  | 'VERIFIED'
  | 'DECLINED';

export type InvestorProfileDto = {
  fullName: FullNameDto;
  countryOfResidence: CountryDto;
  /**
   * @default null
   */
  stateOfResidence: string | null;
  /**
   * @default null
   */
  referralSource: string | null;
  /**
   * @default null
   */
  phoneNumber: string | null;
  /**
   * @default null
   */
  linkedinUrl: string | null;
  /**
   * @default null
   */
  investorType: InvestorTypeEnum | null;
  /**
   * @default false
   */
  acceptedNoAlternativeUse: boolean;
  /**
   * @default false
   */
  acceptedRiskAcknowledgement: boolean;
  /**
   * @default false
   */
  acceptedLegalAcknowledgement: boolean;
  /**
   * @default false
   */
  acceptedAnonymousDistribution: boolean;
  /**
   * @default null
   */
  accreditedInvestorStatus: AccreditedInvestorStatusEnum | null;
  /**
   * @default false
   */
  accreditationConfirmation: boolean;
  /**
   * @default null
   */
  lpInvestingExperience: string | null;
  /**
   * @default null
   */
  deployedAmount: string | null;
  /**
   * @default null
   */
  expectedDeploymentAmount: string | null;
  /**
   * @default null
   */
  netWorth: string | null;
};

export type MandateDto = {
  /**
   * @format uuid
   */
  mandateId: string;
  status: MandateStatusEnum;
  dealSources: any[];
  investmentStrategy: string | null;
  otherStrategy: string | null;
  realEstate: MandateRealEstateDto | null;
  privateEquity: MandatePrivateEquityDto | null;
  trophyAssets: MandateTrophyAssetsDto | null;
  funds: MandateFundsDto | null;
  taxAdvantaged: MandateTaxAdvantagedDto | null;
  instrumentType: string | null;
  otherInstrumentType: string | null;
  syndicationPreference: string | null;
  dealBreakers: string | null;
  minimumReturnTarget: string | null;
  minimumReturnTargetCustomValue: string | null;
  sponsorTrackRecord: string | null;
  geographicalRestrictions: string | null;
  additionalDetails: string | null;
  contactInfo: MandateContactInfoDto;
};

export type MandateDraftDto = {
  dealSources: any[] | null;
  investmentStrategy: string | null;
  otherStrategy: string | null;
  realEstate: MandateRealEstateDto | null;
  privateEquity: MandatePrivateEquityDto | null;
  trophyAssets: MandateTrophyAssetsDto | null;
  funds: MandateFundsDto | null;
  taxAdvantaged: MandateTaxAdvantagedDto | null;
  instrumentType: string | null;
  otherInstrumentType: string | null;
  syndicationPreference: string | null;
  dealBreakers: string | null;
  minimumReturnTarget: string | null;
  minimumReturnTargetCustomValue: string | null;
  sponsorTrackRecord: string | null;
  geographicalRestrictions: string | null;
  additionalDetails: string | null;
  contactInfo: MandateContactInfoDto | null;
  termsAgreed: boolean | null;
};

export type CountryDto = {
  id: number;
  country: string;
};

export type AdminDealDto = {
  /**
   * @format uuid
   */
  dealId: string;
  dealStatus: DealStatusEnum;
  deal: DealDto;
  dealOwner: DealOwnerDto;
  mandate: MandateDto;
  /**
   * @format date-time
   */
  createdAt: string;
  files: DealFileDto[];
};

export type InvestorFullProfileDto = {
  user: UserDto;
  profile: InvestorProfileDto;
  status: InvestorProfileStatusEnum;
};

export type DealRealEstateDto = {
  propertyType: boolean;
  riskReturnProfile: boolean;
  checkSize: boolean;
  geographicalFocus: boolean;
  holdPeriod: boolean;
  projectStage: boolean;
};

export type DealPrivateEquityDto = {
  preferredStrategy: boolean;
  industryFocus: boolean;
  checkSize: boolean;
  controlPreference: boolean;
  companyStage: boolean;
};

export type DealTrophyAssetsDto = {
  assetType: boolean;
  preferredGeography: boolean;
  taxPreferences: boolean;
};

export type DealFundsDto = {
  fundType: boolean;
  fundStage: boolean;
  sectorFocus: boolean;
  checkSize: boolean;
};

export type DealTaxAdvantagedDto = {
  primaryTaxProgram: boolean;
  preferredStructures: boolean;
  geographicFocus: boolean;
};

export type DealStatusEnum = 'pending' | 'matched' | 'approved' | 'rejected';

export type MandateRealEstateDto = {
  propertyType: string | null;
  otherPropertyType: string | null;
  riskReturnProfile: string | null;
  otherRiskProfile: string | null;
  checkSize: string | null;
  geographicalFocus: string | null;
  otherGeography: string | null;
  holdPeriod: string | null;
  projectStage: string | null;
  otherProjectStage: string | null;
};

export type MandatePrivateEquityDto = {
  preferredStrategy: string | null;
  otherStrategy: string | null;
  industryFocus: string | null;
  otherIndustry: string | null;
  checkSize: string | null;
  controlPreference: string | null;
  companyStage: string | null;
};

export type MandateTrophyAssetsDto = {
  assetType: string | null;
  otherAssetType: string | null;
  preferredGeography: string | null;
  geographyDetails: string | null;
  taxPreferences: string | null;
  taxPreferencesDetails: string | null;
};

export type MandateFundsDto = {
  fundType: string | null;
  otherFundType: string | null;
  fundStage: string | null;
  sectorFocus: string | null;
  otherSector: string | null;
  checkSize: string | null;
};

export type MandateTaxAdvantagedDto = {
  primaryTaxProgram: string | null;
  otherTaxProgram: string | null;
  preferredStructures: string | null;
  otherStructure: string | null;
  geographicFocus: string | null;
  geographyDetails: string | null;
};

export type DealOwnerRoleEnum = 'BROKER' | 'SPONSOR' | 'OPERATOR' | 'GP' | 'LP';

export type FullNameDto = {
  firstName: string;
  lastName: string;
};

export type InvestorTypeEnum = 'INDIVIDUAL' | 'FAMILY_OFFICE' | 'ALLOCATOR' | 'SERVICE_PROVIDER';

export type AccreditedInvestorStatusEnum =
  | 'INDIVIDUAL_INCOME_BASED_QUALIFICATION'
  | 'INDIVIDUAL_NET_WORTH_BASED_QUALIFICATION'
  | 'INDIVIDUAL_PROFESSIONAL_CERTIFICATIONS'
  | 'ENTITY_ASSET_BASED_QUALIFICATION'
  | 'ENTITY_INSTITUTIONAL_INVESTORS'
  | 'ENTITY_FAMILY_OFFICES_AND_CLIENTS'
  | 'NON_ACCREDITED';

export type MandateStatusEnum = 'pending' | 'active' | 'declined' | 'cancelled';

export type MandateContactInfoDto = {
  name: string;
  email: string;
  /**
   * @default null
   */
  phone: string | null;
};

export type DealFileDto = {
  filename: string;
  url: string;
};
