/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type ApiTokenResponse = {
  token: string;
};

export type ErrorResponse = {
  code: string;
};

export type GuidResponse = {
  /**
   * @format uuid
   */
  id: string;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type UserLoginDto = {
  email: string;
  /**
   * @maxLength 6
   * @minLength 6
   */
  code: string;
};

export type UserRegistrationDto = {
  email: string;
};
