<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <XSAppIconAssets>Assets.xcassets/AppIcon.appiconset</XSAppIconAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.iOS" />
  </ItemGroup>

  <ItemGroup>
    <ImageAsset Include="Assets.xcassets\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KoboGg\KoboGg.csproj" />
  </ItemGroup>
</Project>
